### ISSUE TITLE
About  java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by LoginGit** [CrazyOrr/FFmpegRecorder#16]
Hi,CrazyOrr:

    Thank you for sharing the code,But I have some problems with porting your code, 
I used the Android Studio to import your project with the following error:
     E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                                                                     Process: com.ksyun.live.demo, PID: 26297
                                                                     java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                         at android.os.AsyncTask$3.done(AsyncTask.java)
                                                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                      Caused by: java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                                         at java.lang.Class.classForName(Native Method)
                                                                         at java.lang.Class.forName(Class.java:308)
                                                                         at org.bytedeco.javacpp.Loader.load(Loader.java:585)
                                                                         at org.bytedeco.javacpp.Loader.load(Loader.java:530)
                                                                         at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1694)
                                                                         at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                                                                         at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129)
                                                                         at com.ksyun.media.streamer.demo.CameraActivity.initRecorder(CameraActivity.java:607)
                                                                         at com.ksyun.media.streamer.demo.CameraActivity.access$1000(CameraActivity.java:93)
                                                                         at com.ksyun.media.streamer.demo.CameraActivity$3.doInBackground(CameraActivity.java:493)
                                                                         at com.ksyun.media.streamer.demo.CameraActivity$3.doInBackground(CameraActivity.java:488)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                         at java.lang.Thread.run(Thread.java:818) 

   This error appears on any phone!

Look forward to your reply!

**Comment by LoginGit** [comment]
I found that my own library includes armeabi，armeabi-v7a，and x86,  So there was a exception.

But how to solve it!

**Comment by CrazyOrr** [comment]
Please refer to issue #8 for workaround.
