### ISSUE TITLE
用东西挡住摄像头，让Preview里面是全黑，不一会就OOM

### ISSUE THREAD

**Issue by gordonpro** [CrazyOrr/FFmpegRecorder#21]
```
Process: com.github.crazyorr.ffmpegrecorder, PID: 10415
java.lang.OutOfMemoryError: Failed to allocate memory within limits: totalBytes = 95M + 600K > maxBytes = 96M
at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:558)
at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
at org.bytedeco.javacpp.BytePointer.allocateArray(Native Method)
at org.bytedeco.javacpp.BytePointer.<init>(BytePointer.java:82)
at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:778)
at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:756)
at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:749)
```

正常情况，我从AS 的Monitor看内存走势，开始录制不久就会有内存抖动，但是回收很正常，不会OOM。 
![image](https://cloud.githubusercontent.com/assets/4123506/23841782/a173b096-07ea-11e7-85e9-475567c24029.png)

我把摄像头挡住，Preview里面是全黑的时候，看Monitor。 内存不抖，涨得很慢，但是不回收，然后就直接OOM. 大概1分钟的时候。

![image](https://cloud.githubusercontent.com/assets/4123506/23841816/ed81b55a-07ea-11e7-8c6e-fe421187c1e9.png)

**Comment by CrazyOrr** [comment]
感谢反馈。
我在Nexus 6(7.0)和Note 2(4.3)上试了一下，暂时无法复现该问题。
请问你用的是什么机型，系统版本？是否每次全黑录制都会出现OOM？
