### ISSUE TITLE
libjniavutil.so: unused DT entry: type 0xf arg 0x18b9d

### ISSUE THREAD

**Issue by lphgithub** [CrazyOrr/FFmpegRecorder#22]
.ffmpegrecorder W/linker: /data/app/com.github.crazyorr.ffmpegrecorder-1/lib/arm/libjniavutil.so: unused DT entry: type 0xf arg 0x18b9d
05-08 20:04:03.393 6712-6775/com.github.crazyorr.ffmpegrecorder I/art: Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>
05-08 20:04:03.397 6712-6775/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                 Process: com.github.crazyorr.ffmpegrecorder, PID: 6712
                                                 java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                     at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.Class.forName(Class.java:324)
                                                     at org.bytedeco.javacpp.Loader.load(Loader.java:585)
                                                     at org.bytedeco.javacpp.Loader.load(Loader.java:530)
                                                     at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1694)
                                                     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                                                     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129)
                                                     at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity.initRecorder(FFmpegRecordActivity.java:415)
                                                     at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity.access$1100(FFmpegRecordActivity.java:50)
                                                     at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity$5.doInBackground(FFmpegRecordActivity.java:288)
                                                     at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity$5.doInBackground(FFmpegRecordActivity.java:283)
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by CrazyOrr** [comment]
Try use [ReLinker](https://github.com/KeepSafe/ReLinker) to load native libs.
See [this issue](https://github.com/bytedeco/javacv/issues/579) and [this](https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29) for details.
