### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by rishabhcha** [CrazyOrr/FFmpegRecorder#25]
It is working fine in kitkat but in marshmallow i'm getting this error:

```
FATAL EXCEPTION: AsyncTask #1
                                                                                    Process: com.github.crazyorr.ffmpegrecorder, PID: 22199
                                                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                        at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                                        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                        at java.lang.Thread.run(Thread.java:818)
                                                                                     Caused by: java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                                                        at java.lang.Class.classForName(Native Method)
                                                                                        at java.lang.Class.forName(Class.java:324)
                                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:585)
                                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:530)
                                                                                        at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1694)
                                                                                        at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                                                                                        at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129)
                                                                                        at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity.initRecorder(FFmpegRecordActivity.java:415)
                                                                                        at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity.access$1100(FFmpegRecordActivity.java:50)
                                                                                        at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity$5.doInBackground(FFmpegRecordActivity.java:288)
                                                                                        at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity$5.doInBackground(FFmpegRecordActivity.java:283)
                                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by CrazyOrr** [comment]
Please refer to issue #8 for [workaround](https://github.com/CrazyOrr/FFmpegRecorder/issues/8#issuecomment-261923515).

**Comment by rishabhcha** [comment]
Thanks for your support
