### ISSUE TITLE
Exception while initialization on FFmpegFrameRecorder

### ISSUE THREAD

**Issue by santoshshikare** [CrazyOrr/FFmpegRecorder#32]
i am getting following error on initialization 
 mFrameRecorder = new FFmpegFrameRecorder(mVideo, videoWidth, videoHeight, 1);

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #6
                  Process: com.ormatheapp, PID: 7325
                  java.lang.RuntimeException: An error occured while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:300)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                      at java.lang.Thread.run(Thread.java:841)
                   Caused by: java.lang.ExceptionInInitializerError
                      at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                      at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129)
                      at com.ormatheapp.CreateOrmaActivity.initRecorder(CreateOrmaActivity.java:524)
                      at com.ormatheapp.CreateOrmaActivity.access$1400(CreateOrmaActivity.java:57)
                      at com.ormatheapp.CreateOrmaActivity$7.doInBackground(CreateOrmaActivity.java:396)
                      at com.ormatheapp.CreateOrmaActivity$7.doInBackground(CreateOrmaActivity.java:391)
                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                      at java.lang.Thread.run(Thread.java:841) 
                   Caused by: java.lang.TypeNotPresentException: Type org/bytedeco/javacpp/avcodec not present
                      at java.lang.Class.getDeclaringClass(Native Method)
                      at org.bytedeco.javacpp.Loader.getEnclosingClass(Loader.java:204)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:567)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:530)
                      at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1694)
                      at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149) 
                      at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129) 
                      at com.ormatheapp.CreateOrmaActivity.initRecorder(CreateOrmaActivity.java:524) 
                      at com.ormatheapp.CreateOrmaActivity.access$1400(CreateOrmaActivity.java:57) 
                      at com.ormatheapp.CreateOrmaActivity$7.doInBackground(CreateOrmaActivity.java:396) 
                      at com.ormatheapp.CreateOrmaActivity$7.doInBackground(CreateOrmaActivity.java:391) 
                      at android.os.AsyncTask$2.call(AsyncTask.java:288) 
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                      at java.lang.Thread.run(Thread.java:841) 
kindly help or suggest to solve this issue 
i have added all the dependency on my gradle file

**Comment by CrazyOrr** [comment]
Did you [config proguard](https://github.com/bytedeco/javacv/wiki/Configuring-Proguard-for-JavaCV) for you project?

**Comment by santoshshikare** [comment]
I have tried to upgrade Proguard but it crash my android stuido

**Comment by santoshshikare** [comment]
Still its giving error after config new proguard

**Comment by CrazyOrr** [comment]
Try to use a newer version of [JavaCV](https://github.com/bytedeco/javacv).

**Comment by santoshshikare** [comment]
Solved
