### ISSUE TITLE
Error in android sdklevel 26

### ISSUE THREAD

**Issue by husseinAYehya** [CrazyOrr/FFmpegRecorder#36]
hi all

when i use the libraries and code in a project with SDK version 26 , an error appears on 
        mFrameRecorder = new FFmpegFrameRecorder(mVideo, videoWidth, videoHeight, 1);

the log :
01-03 12:25:10.401 11112-11112/com.github.crazyorr.ffmpegrecorder E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.github.crazyorr.ffmpegrecorder, PID: 11112
                                                                                    java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                                                        at java.lang.Class.classForName(Native Method)
                                                                                        at java.lang.Class.forName(Class.java:308)
                                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:585)
                                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:530)
                                                                                        at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1694)
                                                                                        at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                                                                                        at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129)
                                                                                        at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity.initRecorder(FFmpegRecordActivity.java:566)
                                                                                        at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity.onCreate(FFmpegRecordActivity.java:264)
                                                                                        at android.app.Activity.performCreate(Activity.java:5977)
                                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2258)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
                                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:148)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5272)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)

**Comment by CrazyOrr** [comment]
Try [this](https://github.com/CrazyOrr/FFmpegRecorder/issues/8#issuecomment-261923515).
