### ISSUE TITLE
UnsatisfiedLinkError: org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by JoyHong** [CrazyOrr/FFmpegRecorder#8]
Dear

Now, i'm using latest code, but in some platform(eg. Meizu 6.0+), it crash with following message.
I don't know how to handle it...

Caused by: java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                               at java.lang.Class.classForName(Native Method)
                                                               at java.lang.Class.forName(Class.java:324)
                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:474)
                                                               at org.bytedeco.javacpp.Loader.load(Loader.java:419)
                                                               at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1559)
                                                               at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                                                               at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129)

**Comment by CrazyOrr** [comment]
Will this error occur on those platforms if you set targetSdkVersion to 22?

**Comment by JoyHong** [comment]
Yes, when i set targetSdkVersion to 22, this issue still occur.

**Comment by CrazyOrr** [comment]
Check out [this](https://github.com/bytedeco/javacpp-presets/wiki/Issues-with-Build-Tools#android-studio) and [this](https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-(a-real-experience)).
P.S. You can use [this tool](https://play.google.com/store/apps/details?id=com.xh.nativelibsmonitor.app&hl=en) to see if those .so libraries are available on your device.

**Comment by JoyHong** [comment]
Dear
I checked with the tool
In the devices work well, it supprot arm64-v8a, armeabi-v7a, armeabi.
In the devices occur crash, it only support armeabi-v7a, armeabi.
Could u please help to support it for me?

**Comment by CrazyOrr** [comment]
I'll look into it, but I don't think arm64-v8a is the problem here. Because on my Nexus 6, which only supports armeabi-v7a and armeabi, this error doesn't occur.

**Comment by hexmonad** [comment]
Hi @JoyHong ,
did you try a manual installation: https://github.com/bytedeco/javacv#manual-installation ?
This is done in this commit: https://github.com/CrazyOrr/FFmpegRecorder/commit/2ab86b649e0e005dd856b2da6aab23ecb893558a
Please check it out.

**Comment by JoyHong** [comment]
btw, does following configuration will effect the result?
ndk {
    abiFilters 'armeabi'
}

**Comment by hexmonad** [comment]
Yes, it does. From https://developer.android.com/studio/projects/add-native-code.html:
> By default, Gradle builds your native library into separate .so files for the ABIs the NDK supports and packages them all into your APK. If you want Gradle to build and package only certain ABI configurations of your native libraries, you can specify them with the **ndk.abiFilters** flag in your module-level build.gradle file

So, if you use "abiFilters 'armeabi'", you should place .so files in the app/src/main/jniLibs/armeabi folder.

**Comment by CrazyOrr** [comment]
I don't think so because there are only armeabi libraries, so you don't need to specify that.

**Comment by hexmonad** [comment]
When you use the tool mentioned here: https://github.com/CrazyOrr/FFmpegRecorder/issues/8#issuecomment-256604614,
do you see libraries under Native Libraries Installed section, like libavutil.so etc. ?

**Comment by JoyHong** [comment]
Yes, I saw them
but, I check the list is the same with my two devices.

**Comment by tingfengainiaini** [comment]
Relinker works for me.
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-(a-real-experience)

**Comment by JoyHong** [comment]
Dear, help me, sorry for my poor knowledge.
Now i got aother crash log, Caused by: java.lang.NoClassDefFoundError: org/bytedeco/javacpp/avutil
I follow the doc to manully in manual-installation, but i can't find any jar files in the javacpp-presets-1.2-bin or javacpp-presets-1.2-src, should i need to compile them?

**Comment by CrazyOrr** [comment]
You should download [javacv-1.2-bin.zip](http://search.maven.org/remotecontent?filepath=org/bytedeco/javacv/1.2/javacv-1.2-bin.zip), and unzip xx-android-arm/x86.jar in it to get .so files.

**Comment by JoyHong** [comment]
Hi
Should i add ffmpeg-android-arm.jar and opencv-android-arm.jar to libs
and remove following configuations?

configurations {
    all*.exclude group: 'org.bytedeco', module: 'javacpp-presets'
}
compile group: 'org.bytedeco', name: 'javacpp', version: '1.2.4'
    compile(group: 'org.bytedeco', name: 'javacv', version: '1.2') {
        exclude group: 'org.bytedeco.javacpp-presets'
    }
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.0.2-1.2'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.0.2-1.2', classifier: 'android-arm'

**Comment by CrazyOrr** [comment]
No, `ffmpeg-android-arm.jar` = `compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.0.2-1.2', classifier: 'android-arm'`, and `opencv-android-arm.jar` is not needed.
You need to put `javacpp.jar`, `javacv.jar`, `ffmpeg.jar`, `ffmpeg-android-arm.jar` in libs.

**Comment by JoyHong** [comment]
Dear CrazyOrr
It still not work in some devices.
but, i found that these devices are 32bit, i suppose it's the key point.
How can i specify use 32bit so?

**Comment by JoyHong** [comment]
I install your project to 32bit device, the same crash will occurs
 Process: com.github.crazyorr.ffmpegrecorder, PID: 26874
                                                   java.lang.RuntimeException: An error occured while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:841)
                                                    Caused by: java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:479)
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:419)
                                                       at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1559)
                                                       at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                                                       at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129)
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity.initRecorder(FFmpegRecordActivity.java:417)
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity.access$1100(FFmpegRecordActivity.java:51)
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity$5.doInBackground(FFmpegRecordActivity.java:287)
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity$5.doInBackground(FFmpegRecordActivity.java:282)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                       at java.lang.Thread.run(Thread.java:841) 
                                                    Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.Class.forName(Class.java:251)
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:474)
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:419) 
                                                       at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1559) 
                                                       at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149) 
                                                       at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129) 
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity.initRecorder(FFmpegRecordActivity.java:417) 
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity.access$1100(FFmpegRecordActivity.java:51) 
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity$5.doInBackground(FFmpegRecordActivity.java:287) 
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity$5.doInBackground(FFmpegRecordActivity.java:282) 
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288) 
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                       at java.lang.Thread.run(Thread.java:841) 
                                                    Caused by: java.lang.NoClassDefFoundError: org/bytedeco/javacpp/avutil
                                                       at java.lang.Class.classForName(Native Method) 
                                                       at java.lang.Class.forName(Class.java:251) 
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:474) 
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:419) 
                                                       at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1559) 
                                                       at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149) 
                                                       at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129) 
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity.initRecorder(FFmpegRecordActivity.java:417) 
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity.access$1100(FFmpegRecordActivity.java:51) 
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity$5.doInBackground(FFmpegRecordActivity.java:287) 
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity$5.doInBackground(FFmpegRecordActivity.java:282) 
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288) 
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                       at java.lang.Thread.run(Thread.java:841) 
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "org.bytedeco.javacpp.avutil" on path: DexPathList[[zip file "/data/app/com.github.crazyorr.ffmpegrecorder-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.github.crazyorr.ffmpegrecorder-1, /vendor/lib, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                       at java.lang.Class.classForName(Native Method) 
                                                       at java.lang.Class.forName(Class.java:251) 
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:474) 
                                                       at org.bytedeco.javacpp.Loader.load(Loader.java:419) 
                                                       at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1559) 
                                                       at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149) 
                                                       at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129) 
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity.initRecorder(FFmpegRecordActivity.java:417) 
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity.access$1100(FFmpegRecordActivity.java:51) 
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity$5.doInBackground(FFmpegRecordActivity.java:287) 
                                                       at com.github.crazyorr.ffmpegrecorder.FFmpegRecordActivity$5.doInBackground(FFmpegRecordActivity.java:282) 
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288) 
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                       at java.lang.Thread.run(Thread.java:841)

**Comment by JoyHong** [comment]
Could u please help to solve it asap?

**Comment by JoyHong** [comment]
Sorry, correct, it not depends 32bit
Meizu 64bit still occurs this crash.....

**Comment by tingfengainiaini** [comment]
@JoyHong 
I have encoutered this today again in Meizu note 3, with javacv1.2. javacpp1.2.4, javacpp presets 1.2.
I used javacv in a sub module of my project, not app module. This time, the relinker do no help.
When I move the relinker function into main ui thread, mainactivity's onCreate for example. It works!
But I have not test other phones yet.
Hope this works for you.

**Comment by JoyHong** [comment]
Dear tingfengainiaini
It works, many thanks!
